### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by ChrisCatCP** [rodrigost23/scoop-gui#1]
i dont know how to build this project

**Comment by rodrigost23** [comment]
You need Visual Studio and the dependencies for Windows App SDK 1.0 and WinUI 3:  
[https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/)

Note that this project is very experimental, and not really functional.

**Comment by ChrisCatCP** [comment]
In fact I have installed windows-app-sdk
it will show this error
I don't know how to fix it
![image](https://user-images.githubusercontent.com/68489543/149287999-09b80db7-661c-4623-a8b0-39e192a24520.png)
![image](https://user-images.githubusercontent.com/68489543/149287944-3a47dda3-9589-4549-916a-ac67adaeac55.png)
